const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const state = { coins: 750, mode: 'ffa', skin: 'Ranger', upgrades: { damage: 0, jump: 0, health: 0, pack: 0 }, owned: ['ak'], consumables: { jump: 0, regen: 0 }, game: null };
const catalog = {
  skins: [['RANGER','Starter tactical look',0],['JUNGLE GHOST','Leaf-camo specialist',400],['DESERT STRIKE','Sandstorm operator',650],['VOLT RUNNER','Electric blue armor',900]],
  guns: [['RARE SHOTGUN','Close-range burst · 2 shells',600,'shotgun'],['EPIC AK','10–30m precision fire',1400,'ak'],['LEGENDARY SNIPER','20–75m devastating shots',2800,'sniper'],['HISTORIC ARSENAL','$19.99 · Premium only','cash','historic']],
  items: [['JUMP BOOST','Jump 1m higher · one match',100,'jump'],['REGENERATION POTION','Restore 50 health · one match',100,'regen'],['UNITE CALL','$2.99 · teleport teammates','cash','call']],
  upgrades: [['AK CALIBRATION','+10% weapon damage',500,'damage'],['SHOCK STOCK','Reduce reload time',750,'reload']],
  body: [['KINETIC LEGS','Higher jump',450,'jump'],['FORTIFIED VEST','+20 max health',700,'health'],['EXPEDITION PACK','Extra item storage',350,'pack']]
};
function updateLobby(){ $('#coinBalance').textContent = state.coins; $('#skinName').textContent = `${state.skin} skin equipped`; }
function openShop(type){ const title = type === 'skins' ? 'CHANGE ROOM' : type === 'guns' ? 'GUNS SHOP' : type === 'items' ? 'BATTLE SHOP' : type === 'upgrades' ? 'GUN UPGRADES' : 'BODY UPGRADES'; $('#modalEyebrow').textContent = type.toUpperCase(); $('#modalTitle').textContent = title; $('#shopContent').innerHTML = catalog[type].map(([name,desc,cost,key]) => `<article class="product"><h3>${name}</h3><p>${desc}</p><button data-buy="${key||name}" data-cost="${cost}" data-type="${type}">${cost === 'cash' ? 'PURCHASE $' : cost === 0 ? 'EQUIPPED' : `BUY · ◉ ${cost}`}</button></article>`).join(''); $('#shopModal').classList.remove('hidden'); }
$$('.menu-card').forEach(b=>b.onclick=()=>openShop(b.dataset.panel)); $('.close').onclick=()=>$('#shopModal').classList.add('hidden');
$('#shopContent').onclick=e=>{const b=e.target.closest('button'); if(!b||b.dataset.cost==='cash'||b.dataset.cost==='0')return; const cost=+b.dataset.cost; if(state.coins<cost){b.textContent='NOT ENOUGH COINS';return} state.coins-=cost; const type=b.dataset.type,key=b.dataset.buy; if(type==='skins'){state.skin=b.closest('.product').querySelector('h3').textContent; $('#shopModal').classList.add('hidden')} else if(type==='items')state.consumables[key]=(state.consumables[key]||0)+1; else if(type==='guns'){state.owned.includes(key)||state.owned.push(key)} else if(key)state.upgrades[key]=(state.upgrades[key]||0)+1; b.textContent='OWNED';b.disabled=true;updateLobby()};
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode});

const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),mapCanvas=$('#mapCanvas'),mctx=mapCanvas.getContext('2d');let keys={},mouse={x:0,y:0,down:false};
const guns={ak:{name:'NORMAL AK',body:2,head:3,range:[10,30],fall:.04,mag:30,reload:.08,color:'#35d4ee'},shotgun:{name:'SHOTGUN',body:5,head:7,range:[0,1],fall:.05,mag:2,reload:1.5,color:'#ffb52e'},sniper:{name:'SNIPER',body:40,head:80,range:[20,75],fall:.02,mag:1,reload:2,color:'#e17eff'}};
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();
function random(a,b){return a+Math.random()*(b-a)}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function makeWorld(){ const biomes=['Jungle Island','Desert Island','Rocky Island','Mountains Island','Plains Island'], biome=biomes[Math.floor(Math.random()*biomes.length)];const items=[];for(let i=0;i<54;i++)items.push({x:random(100,1900),y:random(100,1900),type:['Bandage','First Aid Kit','Grenade','Rare AK'][i%4],poison:Math.random()<.05});const bots=[];for(let i=0;i<19;i++)bots.push({x:random(80,1920),y:random(80,1920),health:100,dead:false,lastShot:0,name:`${['Viper','Nova','Atlas','Echo','Mantis'][i%5]}-${i+1}`,team:state.mode==='team'&&i<4?'blue':'red'});return {biome,items,bots,player:{x:1000,y:1000,health:100+(state.upgrades.health||0)*20,shield:0,gun:'ak',ammo:30,grenades:2,poison:0,bleed:0,vel:0,dead:false},zone:{x:1000,y:1000,r:880},time:0,lastHeal:0,lastStorm:0,feed:[],paused:false,mapVisible:true,matchEnd:false};}
function startGame(){state.game=makeWorld();$('#lobby').classList.add('hidden');$('#game').classList.remove('hidden');$('#modeHud').textContent=state.mode==='ffa'?'FREE FOR ALL':'TEAM MODE · 5 PLAYERS';document.body.requestPointerLock?.();requestAnimationFrame(loop)}$('#playButton').onclick=startGame;
function addFeed(t){const g=state.game;g.feed.unshift(t);g.feed=g.feed.slice(0,4);$('#killFeed').innerHTML=g.feed.map(x=>`<div class="feed">${x}</div>`).join('')}
function screen(p){const g=state.game,pl=g.player;const cameraY=g.view==='third'?80:0;return {x:canvas.width/2+(p.x-pl.x),y:canvas.height/2+cameraY+(p.y-pl.y)}}
function worldPoint(x,y){const p=state.game.player;return{x:p.x+x-canvas.width/2,y:p.y+y-canvas.height/2}}
function update(dt){const g=state.game,p=g.player;if(g.paused||g.matchEnd)return;g.time+=dt;g.zone.r=Math.max(150,880-g.time*.5);let speed=190*(p.bleed>0?.75:1);let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0);if(dx||dy){let l=Math.hypot(dx,dy);p.x=Math.max(20,Math.min(1980,p.x+dx/l*speed*dt));p.y=Math.max(20,Math.min(1980,p.y+dy/l*speed*dt))}p.bleed=Math.max(0,p.bleed-dt);p.poison=Math.max(0,p.poison-dt);if(g.time-p.lastHeal>5){p.health=Math.min(100+(state.upgrades.health||0)*20,p.health+1);p.lastHeal=g.time}if(p.poison&&Math.floor(g.time)%5===0&&g.time-p.lastPoison>1){hurt(p,1,'poison');p.lastPoison=g.time}if(Math.hypot(p.x-g.zone.x,p.y-g.zone.y)>g.zone.r&&g.time-p.lastStorm>10){hurt(p,25,'storm lightning');g.lastStorm=g.time}g.bots.forEach(b=>{if(b.dead)return;let d=dist(b,p);if(d<430&&g.time-b.lastShot>random(.6,1.5)){hurt(p,random(3,9),b.name);b.lastShot=g.time}if(d>190){b.x+=(p.x-b.x)/d*35*dt;b.y+=(p.y-b.y)/d*35*dt}});let nearby=g.items.find(i=>dist(i,p)<48);const prompt=$('#prompt');if(nearby){prompt.textContent=`PRESS F TO PICK UP ${nearby.type.toUpperCase()}`;prompt.classList.remove('hidden')}else prompt.classList.add('hidden');if(p.health<=0)endGame(false);updateHud();}
function hurt(target,amount,source){let dmg=amount;if(target.shield){let s=Math.min(target.shield,dmg);target.shield-=s;dmg-=s}target.health-=dmg;if(target===state.game.player&&source!=='poison'&&source!=='storm lightning')target.bleed=30;if(target.health<=0){target.dead=true;if(target===state.game.player)endGame(false);else{addFeed(`YOU eliminated ${target.name}`);state.game.items.push({x:target.x,y:target.y,type:'Loot Bag',poison:false})}}}
function shoot(){const g=state.game,p=g.player;if(g.paused||g.matchEnd||!mouse.down)return;let gun=guns[p.gun];if(g.time-p.lastShot<gun.reload||p.ammo<=0)return;p.lastShot=g.time;p.ammo--;let aim=worldPoint(mouse.x,mouse.y);let candidates=g.bots.filter(b=>!b.dead&&dist(b,p)<700);let hit=candidates.sort((a,b)=>{let aa=Math.abs(Math.atan2(a.y-p.y,a.x-p.x)-Math.atan2(aim.y-p.y,aim.x-p.x));let bb=Math.abs(Math.atan2(b.y-p.y,b.x-p.x)-Math.atan2(aim.y-p.y,aim.x-p.x));return aa-bb})[0];if(hit&&Math.abs(Math.atan2(hit.y-p.y,hit.x-p.x)-Math.atan2(aim.y-p.y,aim.x-p.x))<.13){let d=dist(hit,p)/35,ideal=d<gun.range[0]?gun.range[0]:d>gun.range[1]?gun.range[1]:d,damage=gun.body*Math.max(.1,1-Math.abs(d-ideal)*gun.fall)*(1+(state.upgrades.damage||0)*.1);hurt(hit,damage,'you');}if(!p.ammo){setTimeout(()=>p.ammo=gun.mag,gun.reload*1000)}}
function grenade(){const g=state.game,p=g.player;if(p.grenades<1||g.paused)return;p.grenades--;let target=worldPoint(mouse.x,mouse.y);g.bots.forEach(b=>{if(!b.dead&&dist(b,target)<70)hurt(b,20,'grenade')});addFeed('GRENADE DETONATED · 20 damage radius')}
function pickup(){const g=state.game,p=g.player;let i=g.items.findIndex(x=>dist(x,p)<48);if(i<0)return;let item=g.items.splice(i,1)[0];if(item.type==='Bandage')p.bleed=0;if(item.type==='First Aid Kit'){p.poison=0;p.health=Math.min(100,p.health+35)}if(item.type==='Grenade')p.grenades++;if(item.poison){p.poison=40;addFeed('⚠ POISONED ITEM — First aid kit cures it')}else addFeed(`PICKED UP ${item.type.toUpperCase()}`)}
function updateHud(){const g=state.game,p=g.player,gun=guns[p.gun];$('#healthText').textContent=Math.max(0,Math.ceil(p.health));$('#healthBar').style.width=`${Math.max(0,p.health)/(100+(state.upgrades.health||0)*20)*100}%`;$('#shieldText').textContent=p.shield;$('#shieldBar').style.width=`${p.shield}%`;$('#weaponName').textContent=gun.name;$('#weaponName').style.color=gun.color;$('#ammoText').textContent=p.ammo;$('#aliveHud').textContent=`ALIVE: ${g.bots.filter(b=>!b.dead).length+1}`;let remain=Math.max(0,90-g.time);$('#timerHud').textContent=`STORM: ${String(Math.floor(remain/60)).padStart(2,'0')}:${String(Math.floor(remain%60)).padStart(2,'0')}`;$('#effects').innerHTML=(p.bleed?'<div style="color:#ff6b6b">● BLEEDING — SLOW</div>':'')+(p.poison?'<div style="color:#c171ff">● POISONED</div>':'');}
function render(){const g=state.game,p=g.player;ctx.fillStyle=g.biome==='Desert Island'?'#b98e45':g.biome==='Rocky Island'?'#65716c':g.biome==='Mountains Island'?'#7e9a88':g.biome==='Jungle Island'?'#1f664c':'#4f9959';ctx.fillRect(0,0,canvas.width,canvas.height);let ox=canvas.width/2-p.x,oy=canvas.height/2-p.y;ctx.strokeStyle='#4a9eac';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(ox-100,oy+300);ctx.bezierCurveTo(ox+300,oy+150,ox+700,oy+500,ox+1100,oy+180);ctx.stroke();for(let x=0;x<2000;x+=100)for(let y=0;y<2000;y+=100){if(((x*7+y*11)%9===0)&&g.biome!=='Desert Island'&&g.biome!=='Rocky Island'){let s=screen({x,y});ctx.fillStyle='#245b37';ctx.beginPath();ctx.arc(s.x,s.y,g.biome==='Jungle Island'?20:12,0,7);ctx.fill()}else if((x+y)%400===0&&g.biome!=='Plains Island'){let s=screen({x,y});ctx.fillStyle='#65605b';ctx.beginPath();ctx.arc(s.x,s.y,10,0,7);ctx.fill()}}let z=screen(g.zone);ctx.strokeStyle='#99d8ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(z.x,z.y,g.zone.r,0,7);ctx.stroke();ctx.strokeStyle='#ff3344aa';ctx.lineWidth=12;ctx.strokeRect(ox,oy,2000,2000);g.items.forEach(i=>{let s=screen(i);ctx.fillStyle=i.poison?'#b54cff':'#ffdf4a';ctx.fillRect(s.x-6,s.y-6,12,12)});g.bots.forEach(b=>{if(b.dead)return;let s=screen(b);ctx.fillStyle=b.team==='blue'?'#41c4ff':'#ff5454';ctx.beginPath();ctx.arc(s.x,s.y,13,0,7);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(s.x-15,s.y-22,30,4);ctx.fillStyle='#5cf56d';ctx.fillRect(s.x-15,s.y-22,30*b.health/100,4)});ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(canvas.width/2,canvas.height/2,14,0,7);ctx.fill();ctx.fillStyle='#0b4250';ctx.beginPath();ctx.arc(canvas.width/2,canvas.height/2,7,0,7);ctx.fill();renderMap()}
function renderMap(){const g=state.game;if(!g.mapVisible){$('#minimap').style.display='none';return}$('#minimap').style.display='block';mctx.fillStyle='#3a8d65';mctx.fillRect(0,0,170,170);mctx.strokeStyle='#8de2f4';mctx.lineWidth=2;mctx.beginPath();mctx.arc(g.zone.x/2000*170,g.zone.y/2000*170,g.zone.r/2000*170,0,7);mctx.stroke();mctx.fillStyle='#fff';mctx.beginPath();mctx.arc(g.player.x/2000*170,g.player.y/2000*170,3,0,7);mctx.fill();if(state.mode==='team')g.bots.filter(b=>b.team==='blue'&&!b.dead).forEach(b=>{mctx.fillStyle='#35caff';mctx.fillRect(b.x/2000*170-2,b.y/2000*170-2,4,4)})}
function endGame(win){const g=state.game;if(g.matchEnd)return;g.matchEnd=true;document.exitPointerLock?.();$('#gameOver').classList.remove('hidden');$('#gameOverTitle').textContent=win?'VICTORY ROYALE':'ELIMINATED';$('#gameOverText').textContent=win?'You survived the storm. +250 Unite Coins':'Your items were dropped in a loot bag.';if(win){state.coins+=250;updateLobby()}}
let last=0;function loop(t){if(!state.game||$('#game').classList.contains('hidden'))return;let dt=Math.min(.05,(t-last||0)/1000);last=t;update(dt);shoot();render();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;const g=state.game;if(!g)return;if(e.key==='F5'){e.preventDefault();g.view=g.view==='third'?'first':'third';addFeed(`${g.view.toUpperCase()}-PERSON VIEW`)}if(e.key==='1')g.player.gun='ak';if(e.key==='2')g.player.gun='shotgun';if(e.key==='3')g.player.gun='sniper';if(e.key.toLowerCase()==='e')grenade();if(e.key.toLowerCase()==='f')pickup();if(e.key.toLowerCase()==='n')g.mapVisible=!g.mapVisible;if(e.key==='Escape'){g.paused=!g.paused;$('#escMenu').classList.toggle('hidden',!g.paused);document.exitPointerLock?.()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});canvas.addEventListener('mousedown',()=>{mouse.down=true;canvas.requestPointerLock?.()});addEventListener('mouseup',()=>mouse.down=false);$('#resume').onclick=()=>{state.game.paused=false;$('#escMenu').classList.add('hidden');canvas.requestPointerLock?.()};$('#leave').onclick=()=>{document.exitPointerLock?.();$('#game').classList.add('hidden');$('#lobby').classList.remove('hidden');$('#gameOver').classList.add('hidden')};$('#settings').onclick=()=>$('#settingsPanel').classList.remove('hidden');$('#settingsBack').onclick=()=>$('#settingsPanel').classList.add('hidden');$('#returnLobby').onclick=$('#leave').onclick;updateLobby();
