const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={coins:750,mode:'ffa',skin:'Ranger',upgrades:{damage:0,jump:0,health:0,pack:0},owned:['ak'],consumables:{jump:0,regen:0},game:null};
const catalog={skins:[['RANGER','Starter tactical look',0],['JUNGLE GHOST','Leaf-camo specialist',400],['DESERT STRIKE','Sandstorm operator',650],['VOLT RUNNER','Electric blue armor',900]],guns:[['RARE SHOTGUN','Close-range burst · 2 shells',600,'shotgun'],['EPIC AK','10–30m precision fire',1400,'ak'],['LEGENDARY SNIPER','20–75m devastating shots',2800,'sniper'],['HISTORIC ARSENAL','$19.99 · Premium only','cash','historic']],items:[['JUMP BOOST','Jump 1m higher · one match',100,'jump'],['REGENERATION POTION','Restore 50 health · one match',100,'regen'],['UNITE CALL','$2.99 · teleport teammates','cash','call']],upgrades:[['AK CALIBRATION','+10% weapon damage',500,'damage'],['SHOCK STOCK','Reduce reload time',750,'reload']],body:[['KINETIC LEGS','Higher jump',450,'jump'],['FORTIFIED VEST','+20 max health',700,'health'],['EXPEDITION PACK','Extra item storage',350,'pack']]};
function updateLobby(){$('#coinBalance').textContent=state.coins;$('#skinName').textContent=`${state.skin} skin equipped`}
function openShop(type){const title={skins:'CHANGE ROOM',guns:'GUNS SHOP',items:'BATTLE SHOP',upgrades:'GUN UPGRADES',body:'BODY UPGRADES'}[type];$('#modalEyebrow').textContent=type.toUpperCase();$('#modalTitle').textContent=title;$('#shopContent').innerHTML=catalog[type].map(([n,d,c,k])=>`<article class="product"><h3>${n}</h3><p>${d}</p><button data-buy="${k||n}" data-cost="${c}" data-type="${type}">${c==='cash'?'PURCHASE $':c===0?'EQUIPPED':`BUY · ◉ ${c}`}</button></article>`).join('');$('#shopModal').classList.remove('hidden')}
$$('.menu-card').forEach(b=>b.onclick=()=>openShop(b.dataset.panel));$('.close').onclick=()=>$('#shopModal').classList.add('hidden');
$('#shopContent').onclick=e=>{const b=e.target.closest('button');if(!b||b.dataset.cost==='cash'||b.dataset.cost==='0')return;const cost=+b.dataset.cost;if(state.coins<cost){b.textContent='NOT ENOUGH COINS';return}state.coins-=cost;const type=b.dataset.type,key=b.dataset.buy;if(type==='skins'){state.skin=b.closest('.product').querySelector('h3').textContent;$('#shopModal').classList.add('hidden')}else if(type==='items')state.consumables[key]=(state.consumables[key]||0)+1;else if(type==='guns'&&!state.owned.includes(key))state.owned.push(key);else state.upgrades[key]=(state.upgrades[key]||0)+1;b.textContent='OWNED';b.disabled=true;updateLobby()};$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode});

const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),mapCanvas=$('#mapCanvas'),mctx=mapCanvas.getContext('2d');let keys={},mouseDown=false,last=0;
const guns={ak:{name:'NORMAL AK',damage:9,mag:30,reload:.08,color:'#d9e5e8'},shotgun:{name:'SHOTGUN',damage:23,mag:2,reload:1.5,color:'#c98b55'},sniper:{name:'SNIPER',damage:48,mag:1,reload:2,color:'#343b40'}};
const map=['11111111111111111111','10000000000000100001','10111101111110101101','10100101000000101001','10100101111110101001','10000100010000100001','11110111010111101111','10000101010000100001','10111101011110111101','10100001000010000001','10101111111010111101','10101000001010100001','10101011101010101101','10001010100010101001','11111010111110101001','10000010000000100001','10111111101111101101','10000000100000000001','10111110111111111101','11111111111111111111'];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),norm=a=>Math.atan2(Math.sin(a),Math.cos(a)),rand=(a,b)=>a+Math.random()*(b-a);function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();function wall(x,y){return map[Math.floor(y)]?.[Math.floor(x)]==='1'}function walkable(x,y){return !wall(x+.18,y+.18)&&!wall(x-.18,y+.18)&&!wall(x+.18,y-.18)&&!wall(x-.18,y-.18)}
function makeWorld(){let b=[[8.5,3.5],[15.5,5.5],[5.5,9.5],[13.5,11.5],[3.5,17.5],[16.5,17.5]].map((p,i)=>({x:p[0],y:p[1],health:100,dead:false,name:['Viper','Nova','Atlas','Echo','Mantis','Rook'][i],cooldown:0,team:state.mode==='team'&&i<2?'blue':'red'}));return{player:{x:2.5,y:2.5,a:.25,health:100+(state.upgrades.health||0)*20,shield:0,gun:'ak',ammo:30,grenades:2,bleed:0,jump:0,vy:0,reload:0,shot:0,dead:false},bots:b,zone:{x:10,y:10,r:13},time:0,paused:false,mapVisible:true,matchEnd:false,feed:[],flash:0}}
function startGame(){state.game=makeWorld();$('#lobby').classList.add('hidden');$('#game').classList.remove('hidden');$('#modeHud').textContent=state.mode==='ffa'?'FREE FOR ALL':'TEAM MODE · 5 PLAYERS';canvas.requestPointerLock?.();last=performance.now();requestAnimationFrame(loop)}$('#playButton').onclick=startGame;
function addFeed(t){let g=state.game;g.feed.unshift(t);g.feed=g.feed.slice(0,4);$('#killFeed').innerHTML=g.feed.map(x=>`<div class="feed">${x}</div>`).join('')}
function ray(x,y,a){let d=0;while(d<24){d+=.025;if(wall(x+Math.cos(a)*d,y+Math.sin(a)*d))return d}return 24}
function update(dt){let g=state.game,p=g.player;if(g.paused||g.matchEnd)return;g.time+=dt;g.zone.r=Math.max(3.5,13-g.time*.018);g.flash=Math.max(0,g.flash-dt);p.shot=Math.max(0,p.shot-dt);p.reload=Math.max(0,p.reload-dt);p.bleed=Math.max(0,p.bleed-dt);let speed=(keys.shift?3.7:2.3)*(p.bleed?.75:1),f=(keys.w?1:0)-(keys.s?1:0),s=(keys.d?1:0)-(keys.a?1:0);if(f||s){let l=Math.hypot(f,s),nx=p.x+(Math.cos(p.a)*f+Math.cos(p.a+Math.PI/2)*s)/l*speed*dt,ny=p.y+(Math.sin(p.a)*f+Math.sin(p.a+Math.PI/2)*s)/l*speed*dt;if(walkable(nx,p.y))p.x=nx;if(walkable(p.x,ny))p.y=ny}if(keys.space&&p.jump===0){p.vy=4.8;p.jump=.01}if(p.jump>0||p.vy){p.vy-=12*dt;p.jump=Math.max(0,p.jump+p.vy*dt);if(!p.jump)p.vy=0}if(Math.hypot(p.x-g.zone.x,p.y-g.zone.y)>g.zone.r&&Math.floor(g.time)%10===0&&g.lastStorm!==Math.floor(g.time)){damage(p,25,'storm lightning');g.lastStorm=Math.floor(g.time)}g.bots.forEach(b=>bot(b,dt));if(p.health<=0)end(false);hud()}
function bot(b,dt){let g=state.game,p=g.player;if(b.dead)return;b.cooldown-=dt;let d=Math.hypot(p.x-b.x,p.y-b.y),a=Math.atan2(p.y-b.y,p.x-b.x),clear=ray(p.x,p.y,a)>d-.2;if(d<8&&b.cooldown<0&&clear){damage(p,rand(5,12),b.name);b.cooldown=rand(.7,1.6)}if(d>3){let nx=b.x+Math.cos(a)*dt*.42,ny=b.y+Math.sin(a)*dt*.42;if(walkable(nx,ny)){b.x=nx;b.y=ny}}}
function damage(t,n,source){let d=n;if(t.shield){let u=Math.min(t.shield,d);t.shield-=u;d-=u}t.health-=d;if(t===state.game.player&&source!=='storm lightning')t.bleed=30;if(t.health<=0){t.dead=true;if(t===state.game.player)end(false);else addFeed(`YOU eliminated ${t.name}`)}}
function shoot(){let g=state.game,p=g.player,gun=guns[p.gun];if(g.paused||g.matchEnd||p.reload||!p.ammo||p.shot)return;p.shot=gun.reload;p.ammo--;g.flash=.07;let hit=g.bots.filter(b=>!b.dead).map(b=>({b,d:Math.hypot(b.x-p.x,b.y-p.y),a:Math.abs(norm(Math.atan2(b.y-p.y,b.x-p.x)-p.a))})).filter(o=>o.a<.07&&ray(p.x,p.y,p.a)>o.d-.2).sort((a,b)=>a.a-b.a||a.d-b.d)[0];if(hit)damage(hit.b,gun.damage*(1+(state.upgrades.damage||0)*.1),'you');if(!p.ammo)reload()}
function reload(){let p=state.game.player,g=guns[p.gun];if(p.reload||p.ammo===g.mag)return;p.reload=p.gun==='ak'?1.05:g.reload;addFeed('RELOADING...');setTimeout(()=>{if(state.game&&p.health>0)p.ammo=g.mag},p.reload*1000)}function grenade(){let g=state.game,p=g.player;if(p.grenades<1)return;p.grenades--;g.bots.forEach(b=>{if(!b.dead&&Math.hypot(b.x-p.x,b.y-p.y)<3)damage(b,20,'grenade')});g.flash=.35;addFeed('GRENADE DETONATED · 20 damage radius')}function heal(){let p=state.game.player;if(p.bleed){p.bleed=0;addFeed('BANDAGE APPLIED')}else{p.health=Math.min(100+(state.upgrades.health||0)*20,p.health+25);addFeed('FIRST AID APPLIED')}}
function hud(){let g=state.game,p=g.player,gun=guns[p.gun],max=100+(state.upgrades.health||0)*20;$('#healthText').textContent=Math.max(0,Math.ceil(p.health));$('#healthBar').style.width=`${clamp(p.health/max*100,0,100)}%`;$('#shieldText').textContent=p.shield;$('#shieldBar').style.width=`${p.shield}%`;$('#weaponName').textContent=gun.name;$('#weaponName').style.color=gun.color;$('#ammoText').textContent=p.ammo;$('#aliveHud').textContent=`ALIVE: ${g.bots.filter(b=>!b.dead).length+1}`;$('#timerHud').textContent=`STORM: ${String(Math.max(0,90-g.time|0)).padStart(2,'0')}s`;$('#effects').innerHTML=(p.bleed?'<div style="color:#ff6b6b">● BLEEDING — 25% SLOW</div>':'')+(p.reload?'<div style="color:#ffd56b">● RELOADING</div>':'')}
function render(){let g=state.game,p=g.player,w=canvas.width,h=canvas.height,mid=h/2-p.jump*45,sky=ctx.createLinearGradient(0,0,0,mid),floor=ctx.createLinearGradient(0,mid,0,h);sky.addColorStop(0,'#172331');sky.addColorStop(1,'#65737c');floor.addColorStop(0,'#364044');floor.addColorStop(1,'#11191e');ctx.fillStyle=sky;ctx.fillRect(0,0,w,mid);ctx.fillStyle=floor;ctx.fillRect(0,mid,w,h-mid);let fov=1.05,cols=Math.ceil(w/2),depth=[];for(let i=0;i<cols;i++){let a=p.a-fov/2+i/cols*fov,d=ray(p.x,p.y,a)*Math.cos(a-p.a),line=Math.min(h*1.6,h/d),x=i*2,shade=clamp(180-d*15,26,155)|0;depth[i]=d;ctx.fillStyle=`rgb(${shade*.72|0},${shade*.82|0},${shade})`;ctx.fillRect(x,mid-line/2,2,line);ctx.fillStyle=`rgba(255,255,255,${clamp(.1-d*.012,0,.08)})`;ctx.fillRect(x,mid-line/2,1,line)}enemies(depth,mid,fov);weapon(w,h);if(g.flash){ctx.fillStyle=`rgba(255,210,100,${g.flash*2})`;ctx.fillRect(0,0,w,h)}if(p.dead){ctx.fillStyle='rgba(110,0,0,.4)';ctx.fillRect(0,0,w,h)}mini()}
function enemies(depth,mid,fov){let g=state.game,p=g.player,w=canvas.width,h=canvas.height;g.bots.filter(b=>!b.dead).map(b=>({b,d:Math.hypot(b.x-p.x,b.y-p.y),a:norm(Math.atan2(b.y-p.y,b.x-p.x)-p.a)})).filter(o=>Math.abs(o.a)<fov*.6).sort((a,b)=>b.d-a.d).forEach(o=>{let x=w/2+o.a/(fov/2)*w/2,z=Math.min(h*.95,h/o.d*.8),i=clamp(x/2|0,0,depth.length-1);if(o.d>depth[i]+.15)return;let y=mid-z*.42;ctx.save();ctx.translate(x,y);ctx.fillStyle=o.b.team==='blue'?'#36b8e2':'#8f2b2e';ctx.fillRect(-z*.17,z*.24,z*.12,z*.4);ctx.fillRect(z*.05,z*.24,z*.12,z*.4);ctx.fillStyle='#27313b';ctx.fillRect(-z*.22,0,z*.44,z*.34);ctx.fillStyle='#b57e61';ctx.beginPath();ctx.arc(0,-z*.11,z*.15,0,7);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(-z*.26,z*.06,z*.52,z*.05);ctx.restore();ctx.fillStyle='#161616';ctx.fillRect(x-z*.18,y-z*.28,z*.36,4);ctx.fillStyle='#46e06b';ctx.fillRect(x-z*.18,y-z*.28,z*.36*o.b.health/100,4)})}
function weapon(w,h){let p=state.game.player,g=guns[p.gun],bob=(keys.w||keys.s||keys.a||keys.d)?Math.sin(state.game.time*12)*8:0,recoil=p.shot/g.reload*18,spin=p.reload?Math.sin((1-p.reload/(p.gun==='ak'?1.05:g.reload))*Math.PI)*130:0;ctx.save();ctx.translate(w*.7,h*.83+bob+recoil);ctx.rotate((spin-10)*Math.PI/180);ctx.fillStyle='#161d22';ctx.fillRect(-w*.08,-h*.06,w*.31,h*.11);ctx.fillStyle=g.color;ctx.fillRect(w*.13,-h*.04,w*.18,h*.035);ctx.fillStyle='#d1b498';ctx.fillRect(-w*.03,h*.04,w*.09,h*.22);ctx.fillStyle='#111';ctx.fillRect(w*.01,-h*.07,w*.04,h*.15);ctx.fillRect(-w*.15,h*.12,w*.15,h*.06);if(state.game.flash){ctx.fillStyle='#ffe998';ctx.beginPath();ctx.moveTo(w*.32,-h*.02);ctx.lineTo(w*.42,-h*.09);ctx.lineTo(w*.38,0);ctx.lineTo(w*.43,h*.06);ctx.closePath();ctx.fill()}ctx.restore()}
function mini(){let g=state.game;if(!g.mapVisible){$('#minimap').style.display='none';return}$('#minimap').style.display='block';mctx.fillStyle='#253c38';mctx.fillRect(0,0,170,170);for(let y=0;y<20;y++)for(let x=0;x<20;x++)if(map[y][x]==='1'){mctx.fillStyle='#778078';mctx.fillRect(x*8.5,y*8.5,8.5,8.5)}mctx.strokeStyle='#9eeaff';mctx.beginPath();mctx.arc(g.zone.x*8.5,g.zone.y*8.5,g.zone.r*8.5,0,7);mctx.stroke();mctx.fillStyle='#fff';mctx.beginPath();mctx.arc(g.player.x*8.5,g.player.y*8.5,3,0,7);mctx.fill();if(state.mode==='team')g.bots.filter(b=>b.team==='blue'&&!b.dead).forEach(b=>{mctx.fillStyle='#38c9ff';mctx.fillRect(b.x*8.5-2,b.y*8.5-2,4,4)})}
function end(win){let g=state.game;if(g.matchEnd)return;g.matchEnd=true;document.exitPointerLock?.();const show=()=>{$('#gameOver').classList.remove('hidden');$('#gameOverTitle').textContent=win?'VICTORY ROYALE':'ELIMINATED';$('#gameOverText').textContent=win?'You survived the storm. +250 Unite Coins':'Your character falls and leaves a loot bag.'};if(win){state.coins+=250;updateLobby();show()}else setTimeout(show,650)}
function loop(t){if(!state.game||$('#game').classList.contains('hidden'))return;let dt=Math.min(.04,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;let g=state.game;if(!g)return;if(e.code==='Space')e.preventDefault();if(e.key==='1')g.player.gun='ak';if(e.key==='2')g.player.gun='shotgun';if(e.key==='3')g.player.gun='sniper';if(e.key.toLowerCase()==='r')reload();if(e.key.toLowerCase()==='e')grenade();if(e.key.toLowerCase()==='f')heal();if(e.key.toLowerCase()==='n')g.mapVisible=!g.mapVisible;if(e.key==='F5'){e.preventDefault();addFeed('FIRST-PERSON CAMERA')}if(e.key==='Escape'){g.paused=!g.paused;$('#escMenu').classList.toggle('hidden',!g.paused);document.exitPointerLock?.()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('mousedown',()=>{mouseDown=true;shoot();canvas.requestPointerLock?.()});addEventListener('mouseup',()=>mouseDown=false);addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state.game&&!state.game.paused)state.game.player.a+=e.movementX*.0024});setInterval(()=>{if(mouseDown&&state.game)shoot()},45);$('#resume').onclick=()=>{state.game.paused=false;$('#escMenu').classList.add('hidden');canvas.requestPointerLock?.()};$('#leave').onclick=()=>{document.exitPointerLock?.();$('#game').classList.add('hidden');$('#lobby').classList.remove('hidden');$('#gameOver').classList.add('hidden')};$('#settings').onclick=()=>$('#settingsPanel').classList.remove('hidden');$('#settingsBack').onclick=()=>$('#settingsPanel').classList.add('hidden');$('#returnLobby').onclick=$('#leave').onclick;updateLobby();
